### ISSUE TITLE
How can I write cluster.npy?

### ISSUE THREAD

**Issue by B3tty-x** [BartBruininks/mdvwhole#36] opened 2022-09-29 09:48 UTC
Hi,
I'm trying to restore a 10-mer trajectory, but I don't know how the .npy file format should be written. Could you please provide an example? 
Thanks.

**Comment by BartBruininks** [comment] 2022-09-29 13:49
Dear user,

You do not need to specify any .npy. you only need to specify the protein selection with the selection flag. If your system contains more than just the 10mer (except solvents). It might be wise to add that to the selection too. In case you want to create a custom .npy for segmentation (more advanced but usually not required). The format is [nframes, natoms] where the values are the segment id per atom (integer).

Feel free to ask more questions if you still have issues,. However it would be useful to know the whole complete and the terminal input you specify.

Cheers,

Bart

**Comment by BartBruininks** [comment] 2022-09-29 14:28
If you are using an atomistic system you can run the following:

mdvwhole -f your.gro -x your.xtc -sel 'protein' -wa True

If you use a martini system of proteins in water use:

mdvwhole -f your.gro -x your.xtc -wa True

For more examples look at the examples in the readme of this repository.

**Comment by BartBruininks** [comment] 2022-10-04 11:43
Please let me know if the problem is resolved. Also, if it did work, feel free to share a snapshot of the system in this thread. I'd love to see things being whole :D

**Comment by B3tty-x** [comment] 2022-10-14 08:37
> 
Hello, sorry for taking so long to reply.
I've tried the commands you've listed and haven't gotten much improvement.
In addition, I have some questions about the natoms option of ndp. Does it refer to the number of atoms? For example,
nframes, natoms
1, 2657
2, 2657

Thanks.

**Comment by BartBruininks** [comment] 2022-10-14 09:03
Could you please tell me what you system is and what your solvent is? Also what force field etc. I think you are either using a non-standard solvent or you are running atomistically. In which you have to change your selection. There is no ndp required. The matrix shape should be a binary .npy file generated by numpy in python which can be exported. However, like I said before you probably do not need it.

You can also send a single gro file or something similar to me, I will try it and give you the command to use.

**Comment by BartBruininks** [comment] 2022-10-14 09:10
An example .npy file shape for a 5 atom system with 6 frames:

clusters = np.array([
[1,2,1,3,4],
[1,2,1,3,1].
[1,2,1,3,1],
[1,2,1,1,1],
[1,1,1,1,1],
[1,1,1,1,1],
])

print(cluster.shape) => (6,5)

As you can see there is a cluster assigned to each atom in each frame. The story in this clustering is that over time everything clumps up.

**Comment by B3tty-x** [comment] 2022-10-14 09:42
> The system is made up of ten cyclic peptides. Tip3p is used in the simulation, but the water is removed when dealing with the trajectory. 
I have sent it to your email address by gro. Thank you for your help.

**Comment by BartBruininks** [comment] 2022-10-20 11:28
In the end mdwhole was working, the issue was that after the fragments are made whole. Betty would like to also make the trajectory continuous, (or as continoous as possible). This is currently not a feature of MDVWhole.

**Closed by BartBruininks** 2022-10-20 11:28 UTC
